### PR TITLE
2 commits - I hope.

### PR DESCRIPTION
**Pull request by idelrich**
Commit 9075739 needs to be dumped - can't work out how to "uncommit" things.
Commit ba77393 should be the correct changes in the correct place.

### CODE REVIEW

**Comment by 3breadt** [comment]
I think I have to manually merge the changes to the main branch. 

But I will not include the extensions to NSObject, only to NSString and NSNumber. I find the methods on the NSObject misleading, and they do not really make sense in my opinion. Why should NSDictionary.intValue() be 0 or NSData.boolValue() be false? If the user sees such an API he may use it expecting actual conversion or interpretation (e.g. interpret the byte content of a NSData object as a integer/string/bool). And this is only the case for NSString and NSNumber.

**Comment by idelrich** [comment]
Understood - 

One approach to that would be to have NSObject (base class) throw a type exception for those methods. That allows a programmer who has “extracted” an object which he “knows” is really an NSNumber still get away with calling the intValue method, etc. The way Objective-C reflection works, that is an approach we can use, and it would through an exception if miss-used.

Stephen

**Comment by 3breadt** [comment]
I reimplemented the value methods for NSString according to the behavior of the core foundation methods (See https://developer.apple.com/reference/foundation/nsstring). A simple intParse is not enough to mimic the original behavior. I've also added stringValue to NSNumber.

See commits 58ae8f17ba75b1f098fa4cb8e72a6539cf478bee and 092356bf77547da9eaa92e8e6a82da4ab0207636.

The NSObject base class will not be extended by these methods. Please cast any NSObject instance to the appropriate class to use these methods.

**Comment by idelrich** [comment]
Cool. I think this is a good improvement.

Stephen

**Pull request closed without merging**
