### PR TITLE
Android trailing bits bug

### PR DESCRIPTION
**Pull request by lumley**
There seems to be a problem in Android when using the "read" method without specifying the maximum size to read. In the last iteration seems to return the buffer size as read, regardless of the actual amount of bytes read. Given that the Binary Plist format maps the size of the file at the trailing bits, the size read will always be wrong usually resulting in an OutOfMemoryError.

Solution was to roll back to the last version where this worked correctly, both in Java and Android.

### CODE REVIEW

**Comment by claunia** [comment]
Hi @lumley , can you provide an example plist to test, or a test case. Specifically to test my C# port of the library.

**Comment by lumley** [comment]
Hi  @claunia, I currently don't have the file that was failing at hand. I have quickly created a test project and tried with some other plists, which are working. I will come back to you the moment I get the file back and add it to the test project.

**Comment by claunia** [comment]
Hi @lumley , very much appreciated. Do you know how to use JUnit?

If so it would be preferable you implement a test in https://github.com/3breadt/dd-plist/tree/master/src/test/java/com/dd/plist/test using JUnit so any change code that may cause a regression with this issue is catch.

If not, just search for JUnit, you'll see it's pretty easy, mostly implement a class doing the test, calling some special JUnit methods for comparison and assertion. :p

Thanks in advance.

**Comment by lumley** [comment]
Hi @claunia,

thank you for the feedback, I can attach the file (or create a similar one). Unfortunately the error has occurred only on Android devices and this is a Java-only project, and I understand it should remain that way.

In order to run these tests in Android (in a device) we would either need to set Android tests, move the test files into an "assets" folder and then load from the system or add extra code that can handle this.

I will first try to get the file and a project that proves the issue, otherwise, there is no point in merging these changes :smile:

**Comment by claunia** [comment]
Hi @lumley ,

I know that there's JUnit for Android, but Java is not my platform. Google seems to provide a quite complete explanation on how to use JUnit.

Nonetheless, in .NET, you can use compiler definitions to be sure some code is only executed on a determined framework version (or Windows Phone e.g.).

If it affects only Android, have you checked if it's something Dalvik exclusive or also happens on ART?

**Comment by lumley** [comment]
Ok @claunia, I haven't forgotten about you. I was able to reproduce the issue, I will post it here and the code in the test project this afternoon when I have a bit more time. It is not only a file, it is the combination of a specific file + using a GZip input stream.

About testing JUnit in Android, it is indeed supported, but the issue is not running the tests, but running *certain* tests. Currently dd-plist tests depend on loading binary plist files from the system, this is not something you can do in an Android test as they don't run in the system, but in the device (external resources need to be archived and accessed via Android-specific methods). There are some hacks that Android provides in order to access some assets in a fully compatible Java-way, but this is still not desired for this project. Nevertheless, I haven't had time to determine if it is an Android only or Java issue.

I will come back this afternoon and explain the issue (when I can identify it exactly). Thank you very much for the help so far.

**Comment by lumley** [comment]
Added a test case with the bug, feel free to run it on the old code to see that it would crash with "java.lang.OutOfMemoryError: Java heap space".

### Scenario
Read a file that:
 * is Binary plist
 * is zip compressed
 * the file is bigger than the buffer used to read the bytes (if we read bytes in 512 Bytes chunks, the file should be bigger than 512 Bytes)
 * the file is not a multiple of the buffer size (if we read bytes in 512 Bytes chunks, dividing the file size by 512 should return a float)

### Expected result
 * The Byte array read from the GZIPInputStream should include only the bytes contained inside the stream, uncompressed

### Actual result
 * The Byte array read from the GZIPInputStream actually includes the last chunk of data read from the last iteration in the buffer used

The issue does occur in Java too, not only Android.

See [android project to prove bug and solution in Android](https://github.com/lumley/dd-plist-trailing-bits-test)

**Comment by 3breadt** [comment]
I have added a JUnit test for this issue and fixed it. Thank you for pointing out this issue and giving such detailed information.

**Comment by lumley** [comment]
@3breadt I am very grateful that I could help in fixing the bug, but next time please instead of copying the code from the pull request simply point me out what elements you didn't like from the pull request so I can accommodate my style to the desired of this library (and learn what did I do wrong). I still have more changes I think it could benefit from.

**Comment by 3breadt** [comment]
@lumley Sorry, I did not mean to make you think that your code was not to my liking. I just wanted to implement this for myself from scratch so as to better understand where the problem originates and what exactly solves the erroneous behavior.

**Pull request closed without merging**
