### PR TITLE
Pojo Serializer/Deserializer

### PR DESCRIPTION
**Pull request by hannes-angst**
This change allows to translate between pojo to NS*.

### CODE REVIEW

**Comment by 3breadt** [comment]
Thanks for improving the de-/serialization bit, looks good.

**Comment by 3breadt** [comment]
After merging I realized the code needed quite some improvements. The code lacked JavaDoc for the public methods. Also your code was not compatible with JRE 1.6, which is the target of the project. Additionally you did not deserialize byte arrays as NSData objects, which would be the proper representation. I fixed that in 4a086b5d7745a7c1a931bdafd87930267e62da57

**Comment by hannes-angst** [comment]
Awesome!
It would be be cool if you could add a testcase for the `NSData` special treatment, so that this kind of error does not occur again.
I did not dare to change the jre version. Nor did I want to break things so I left the NS* object's methods as they were. Thanks for the integration. The wrap methods should check, if the object parameter's a NS* object already.

One other thing I did not handle is the `UID` object.  It comes with a special key-value pair.  I'm not that fluent with the p-list specifications but either the key part should override the dictionary key or we need to check the pojo's substructure to parse it right.

**Comment by 3breadt** [comment]
I updated the existing test cases to check for conversion to/from NSData, but I did not extensively check the coverage of that special case.

I added the check for already being a NSObject to the fromJavaObject method.

UIDs only occur in property lists created by NSKeyedArchiver, support for that is quite limited. The implementation for that is very rudimentary. To actually support it also for de-/serialization would need some redesign of the class, I believe. At the moment the UID class does not even correspond to the actual meaning of the UID in its context, which is just a 32-bit integer.

**Pull request merged**
